apiVersion: v1
kind: Secret
metadata:
  name: mrrm-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  authing-app-id: {{ .Values.secrets.authingAppId | quote }}
  authing-app-secret: {{ .Values.secrets.authingAppSecret | quote }}
  authing-callback-url: "https://{{ (index .Values.ingress.hosts 0).host }}/api/v1/auth/sso/callback"
